# Generated by Django 5.2.17 on 2026-08-08 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostics', '0001_initial'),
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diagnostics.diagnosticattempt'),
        ),
        migrations.AddField(
            model_name='diagnosticquestion',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diagnostics.diagnostic'),
        ),
        migrations.AddField(
            model_name='diagnosticquestion',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_questions', to='roles.skill'),
        ),
        migrations.AddField(
            model_name='diagnosticanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diagnostics.diagnosticquestion'),
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='diagnostics.diagnosticattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosticanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
