# Generated by Django 5.2.17 on 2026-08-09 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_initial'),
        ('roles', '0002_ai_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticattempt',
            name='active_turn_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticattempt',
            name='current_stage',
            field=models.CharField(choices=[('FOUNDATION', 'Foundation'), ('SCENARIO', 'Scenario'), ('DEBUGGING', 'Debugging'), ('CODING', 'Coding'), ('CODE_REVIEW', 'Code review')], default='FOUNDATION', max_length=32),
        ),
        migrations.AddField(
            model_name='diagnosticattempt',
            name='gap_report',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosticattempt',
            name='goal',
            field=models.CharField(blank=True, choices=[('ROLE_SWITCH', 'Role switch'), ('CURRENT_ROLE', 'Current role')], default='ROLE_SWITCH', max_length=32),
        ),
        migrations.AddField(
            model_name='diagnosticattempt',
            name='skill_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagnosticattempt',
            name='stage_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosticattempt',
            name='transfer_report',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='DiagnosticTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=1)),
                ('stage', models.CharField(choices=[('FOUNDATION', 'Foundation'), ('SCENARIO', 'Scenario'), ('DEBUGGING', 'Debugging'), ('CODING', 'Coding'), ('CODE_REVIEW', 'Code review')], max_length=32)),
                ('difficulty', models.CharField(default='MEDIUM', max_length=32)),
                ('question_type', models.CharField(default='FREE_TEXT', max_length=32)),
                ('question_payload', models.JSONField(blank=True, default=dict)),
                ('answer_text', models.TextField(blank=True, default='')),
                ('evaluation', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASKED', 'Asked'), ('ANSWERED', 'Answered'), ('EVALUATED', 'Evaluated'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='diagnostics.diagnosticattempt')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_turns', to='roles.skill')),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'unique_together': {('attempt', 'ordering')},
            },
        ),
        migrations.CreateModel(
            name='SkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=32)),
                ('score', models.FloatField(default=0.0)),
                ('evaluation', models.JSONField(blank=True, default=dict)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('source_type', models.CharField(default='diagnostic_turn', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidence', to='diagnostics.diagnosticattempt')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidence', to='roles.skill')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_evidence', to='diagnostics.diagnosticturn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
