# Generated by Django 5.2.17 on 2026-08-09 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
        ('diagnostics', '0003_ai_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('sharpen_current', 'Sharpen current role'), ('switch_role', 'Switch role')], max_length=32)),
                ('target_role', models.CharField(blank=True, default='', max_length=255)),
                ('current_role', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('AWAITING_ANSWERS', 'Awaiting answers'), ('SYNTHESIZING', 'Synthesizing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=32)),
                ('current_block', models.CharField(blank=True, choices=[('A', 'Block A'), ('B', 'Block B')], max_length=8, null=True)),
                ('current_stage', models.CharField(blank=True, choices=[('FOUNDATIONAL', 'Foundational'), ('SCENARIO', 'Scenario'), ('DEBUGGING', 'Debugging'), ('CODING', 'Coding'), ('FIND_ISSUES', 'Find issues')], max_length=32, null=True)),
                ('synthesis', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticRoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_modality', models.CharField(choices=[('THEORY', 'Theory'), ('CODING', 'Coding'), ('RESEARCH', 'Research'), ('DEFEND', 'Defend'), ('DIAGNOSE', 'Diagnose'), ('ARCHITECT', 'Architect'), ('EXPLAIN_CODE', 'Explain code'), ('USE_AI', 'Use AI'), ('COMMUNICATE', 'Communicate')], max_length=32)),
                ('topic', models.CharField(max_length=512)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_roadmap_items', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_roadmap_items', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_items', to='diagnostics.diagnosticsession')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('A', 'Block A'), ('B', 'Block B')], max_length=8)),
                ('stage', models.CharField(choices=[('FOUNDATIONAL', 'Foundational'), ('SCENARIO', 'Scenario'), ('DEBUGGING', 'Debugging'), ('CODING', 'Coding'), ('FIND_ISSUES', 'Find issues')], max_length=32)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question_text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASKED', 'Asked'), ('ANSWERED', 'Answered')], default='ASKED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diagnostics.diagnosticsession')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('session', 'block', 'stage', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='diagnostics.sessionquestion')),
            ],
        ),
    ]
