# Generated by Django 5.2.17 on 2026-08-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_diagnostic_session_block_ab'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('competency_areas', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'role taxonomies',
                'ordering': ['role_name'],
            },
        ),
        migrations.AddField(
            model_name='sessionanswer',
            name='exposure_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionquestion',
            name='competency_area',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='target_taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='diagnostics.roletaxonomy'),
        ),
    ]
