# Generated by Django 5.2.17 on 2026-08-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_role_taxonomy_block_b_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('domain_name', models.CharField(max_length=255)),
                ('competency_areas', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'domain taxonomies',
                'ordering': ['domain_name'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='assessment_competencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='selected_domains',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='diagnostics.domaintaxonomy'),
        ),
    ]
