# Generated by Django 5.x

from django.db import migrations


def seed_domains(apps, schema_editor):
    DomainTaxonomy = apps.get_model("diagnostics", "DomainTaxonomy")
    defaults = [
        {
            "slug": "ai-augmented",
            "domain_name": "AI-Augmented Engineering",
            "competency_areas": [
                "prompt_engineering",
                "llm_api_integration",
                "rag_basics",
                "ai_tooling_workflow",
                "eval_and_guardrails",
            ],
        },
        {
            "slug": "system-design",
            "domain_name": "System Design & Architecture",
            "competency_areas": [
                "service_boundaries",
                "scalability_patterns",
                "data_modeling",
                "caching_and_consistency",
                "api_contract_design",
            ],
        },
        {
            "slug": "reliability",
            "domain_name": "Reliability & Performance",
            "competency_areas": [
                "observability",
                "latency_debugging",
                "failure_modes",
                "capacity_and_load",
                "incident_response",
            ],
        },
        {
            "slug": "communication",
            "domain_name": "Technical Communication",
            "competency_areas": [
                "design_reviews",
                "rfc_writing",
                "stakeholder_explanation",
                "tradeoff_defense",
                "mentoring_and_feedback",
            ],
        },
    ]
    for row in defaults:
        DomainTaxonomy.objects.get_or_create(
            slug=row["slug"],
            defaults={
                "domain_name": row["domain_name"],
                "competency_areas": row["competency_areas"],
            },
        )


def unseed_domains(apps, schema_editor):
    DomainTaxonomy = apps.get_model("diagnostics", "DomainTaxonomy")
    DomainTaxonomy.objects.filter(
        slug__in=[
            "ai-augmented",
            "system-design",
            "reliability",
            "communication",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0006_domain_taxonomy_assessment_competencies"),
    ]

    operations = [
        migrations.RunPython(seed_domains, unseed_domains),
    ]
