# Generated by Django 5.2.17 on 2026-08-10 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0008_static_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_area', models.CharField(db_index=True, max_length=255)),
                ('stat_text', models.TextField()),
                ('source_name', models.CharField(max_length=255)),
                ('source_date', models.CharField(blank=True, default='', max_length=64)),
                ('as_of', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['competency_area', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuickScoreQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], max_length=32)),
                ('competency_area', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['track', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticroadmapitem',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='not_started', max_length=32),
        ),
        migrations.AlterField(
            model_name='diagnosticroadmapitem',
            name='challenge_modality',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('CODING', 'Coding'), ('RESEARCH', 'Research'), ('DEFEND', 'Defend'), ('DIAGNOSE', 'Diagnose'), ('ARCHITECT', 'Architect'), ('EXPLAIN_CODE', 'Explain code'), ('USE_AI', 'Use AI without skill atrophy'), ('COMMUNICATE', 'Communicate')], max_length=32),
        ),
        migrations.AlterField(
            model_name='frameworktopic',
            name='framework_name',
            field=models.CharField(choices=[('react', 'React'), ('nextjs', 'Next.js'), ('django', 'Django'), ('fastapi', 'FastAPI'), ('postgresql', 'PostgreSQL')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='fundamentalstopic',
            name='language_family',
            field=models.CharField(choices=[('javascript', 'JavaScript / TypeScript'), ('python', 'Python'), ('sql', 'SQL')], max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='QuickScoreAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], max_length=32)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('band', models.CharField(choices=[('solid_foundation', 'Solid Foundation'), ('emerging_gaps', 'Emerging Gaps'), ('at_risk', 'At Risk of Falling Behind'), ('significant_gap', 'Significant Gap')], max_length=32)),
                ('paragraph_text', models.TextField(blank=True, default='')),
                ('highlight_areas', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_score_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickScoreParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(choices=[('solid_foundation', 'Solid Foundation'), ('emerging_gaps', 'Emerging Gaps'), ('at_risk', 'At Risk of Falling Behind'), ('significant_gap', 'Significant Gap')], max_length=32)),
                ('track', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], max_length=32)),
                ('body_text', models.TextField()),
            ],
            options={
                'ordering': ['track', 'band'],
                'unique_together': {('band', 'track')},
            },
        ),
        migrations.CreateModel(
            name='QuickScoreChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='diagnostics.quickscorequestion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SkillAreaFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_area', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('strong', 'Strong'), ('partial', 'Partial'), ('gap', 'Gap')], max_length=16)),
                ('body_text', models.TextField()),
            ],
            options={
                'ordering': ['competency_area', 'level'],
                'unique_together': {('competency_area', 'level')},
            },
        ),
    ]
