# Generated by Django 5.2.17 on 2026-08-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0009_v3_core_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsession',
            name='difficulty_bump',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
