# Generated by Django 5.2.17 on 2026-08-08 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userskillgap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gapevidence',
            name='user_skill_gap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='gaps.userskillgap'),
        ),
        migrations.AlterUniqueTogether(
            name='userskillgap',
            unique_together={('user', 'skill')},
        ),
    ]
