# Generated by Django 5.2.17 on 2026-08-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='known_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_role_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
