# Generated by Django 5.2.17 on 2026-08-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_target_label_known_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_learn_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
