# Generated by Django 5.2.17 on 2026-08-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_target_learn_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diagnostic_cycle',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='diagnostic_difficulty_bump',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
