# Generated by Django 5.2.17 on 2026-08-08 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengeskill',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_skills', to='challenges.challenge'),
        ),
        migrations.AddField(
            model_name='challengeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_skills', to='roles.skill'),
        ),
        migrations.AddField(
            model_name='confidencerating',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confidence', to='challenges.challengeattempt'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='challenges.challenge'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='daily_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='challenges.dailychallenge'),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='challenges.challengeattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeskill',
            unique_together={('challenge', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='dailychallenge',
            unique_together={('user', 'date')},
        ),
    ]
