# Generated by Django 5.2.17 on 2026-08-10 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='directions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='preferred_difficulty_bias',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='modality',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('CODING', 'Coding'), ('RESEARCH', 'Research'), ('DEFEND', 'Defend'), ('DIAGNOSE', 'Diagnose'), ('ARCHITECT', 'Architect'), ('EXPLAIN_CODE', 'Explain code'), ('USE_AI', 'Use AI without skill atrophy'), ('COMMUNICATE', 'Communicate')], max_length=32),
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeDebrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AWAITING_SELF_RATE', 'Awaiting self-rate'), ('AWAITING_FOLLOWUPS', 'Awaiting follow-ups'), ('COMPLETED', 'Completed')], default='AWAITING_SELF_RATE', max_length=32)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('follow_up_answers', models.JSONField(blank=True, default=dict)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('next_focus', models.TextField(blank=True, default='')),
                ('checklist_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debrief', to='challenges.challengeattempt')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeModelAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_text', models.TextField()),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_answer', to='challenges.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeRubricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('strength_fragment', models.TextField(blank=True, default='')),
                ('gap_fragment', models.TextField(blank=True, default='')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_items', to='challenges.challenge')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('rubric_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='challenges.challengerubricitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
