# Generated by Django 5.2.17 on 2026-08-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('operation', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(default='ok', max_length=16)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
