# Generated by Django 5.2.17 on 2026-08-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic'), ('CHALLENGE', 'Challenge'), ('DEBRIEF', 'Debrief')], max_length=32)),
                ('reference_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
